In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import keras
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [5]:
dt = pd.read_csv('heart_cleveland_upload.csv')
dt.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   69    1   0       160   234    1        2      131      0      0.1      1   
1   69    0   0       140   239    0        0      151      0      1.8      0   
2   66    0   0       150   226    0        0      114      0      2.6      2   
3   65    1   0       138   282    1        2      174      0      1.4      1   
4   64    1   0       110   211    0        2      144      1      1.8      1   

   ca  thal  condition  
0   1     0          0  
1   2     0          0  
2   0     0          0  
3   1     0          1  
4   0     0          0

In [6]:
X = dt.drop(columns='condition')
X.shape

(297, 13)

In [7]:
y = dt['condition']
y.shape

(297,)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size= 0.2)
X_train.shape, X_test.shape

((237, 13), (60, 13))

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [10]:
X_train[0], X_train[0][1]

(array([-1.28971679,  0.72734604,  0.90324872, -0.66766219, -1.29709962,
        -0.42320737,  1.06550001, -1.31734051,  1.560379  ,  1.25143969,
         0.67919832, -0.69877922,  1.25304084]),
 0.7273460373608398)

In [11]:
def sigmoid(z):
    s = 1/(1 + np.exp(-z))
    return s


In [12]:
X_train.shape

(237, 13)

In [13]:
def layer_compute(x, w, b):
    
    a = [[3][x.shape[0]]]
    
    return a

# yaha jhol hai filhal 

In [14]:
w1 = np.array( [[-8.93, 0.29, 12.9], 
                [-0.1, -7.73, 0.96], 
                [0, 1, 2], 
                [0, 1, 2], 
                [0, 1, 2], 
                [0, 1, 2], 
                [0, 1, 2], 
                [0, 1, 2], 
                [0, 1, 2], 
                [0, 1, 2], 
                [0, 1, 2], 
                [0, 1, 2], 
                [0, 1, 2]] )
b1 = np.array( [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5] )  #Ye bhi 13 values hoge, because we have 13 parameters


w2 = np.array( [[4.4, -0.29]])
b2 = np.array( [-8.2])



In [15]:
X_train[0]
# w[0][1]
# w.shape[1]

# X_train[0]

array([-1.28971679,  0.72734604,  0.90324872, -0.66766219, -1.29709962,
       -0.42320737,  1.06550001, -1.31734051,  1.560379  ,  1.25143969,
        0.67919832, -0.69877922,  1.25304084])

In [16]:
layer1 = layer_compute(X_train, w1, b1)
layer1 = np.array([layer1])
layer2 = layer_compute(layer1, w2, b2)
layer2 = np.array([layer2])
# layer1
# layer2

# layer1.shape

IndexError: list index out of range

In [ ]:
layer2

array([[0.01770884]])